services:
  wytness-backend:
    container_name: wytness-backend
    env_file:
      - .env
    environment:
      NODE_ENV: development
      POSTGRES_HOST: wytness-postgres
      DATABASE_URL: >
        postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@wytness-postgres:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
        PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      wytness-postgres:
        condition: service_healthy
    networks:
      - wytness-net

  wytness-postgres:
    image: postgres:15
    container_name: wytness-postgres
    env_file:
      - .env
    environment:
      POSTGRES_HOST: wytness-postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - wytness-net
    healthcheck:
      test: "pg_isready --username=${POSTGRES_USER} --dbname=${POSTGRES_DB}"
      interval: 2s
      timeout: 10s
      retries: 5

networks:
  wytness-net:
    external: false

volumes:
  pgdata:
